import = [
"~/.config/alacritty/keybindings.toml",
"~/.config/alacritty/color_scheme/github_dark_tritanopia.toml",
]

live_config_reload = true

[env]
TERM = "alacritty"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
dynamic_title = true
opacity = 0.9
padding = { x = 2, y = 0 }

[window.dimensions]
columns = 150
lines = 40
