git:
  parseEmoji: true

gui:
  language: 'ja'
  nerdFontsVersion: "3"

os:
  editPreset: "nvim"

customCommands:
  - key: "<c-c>"
    context: "files"
    description: 'commit files with format'
    prompts:
      - type: "menu"
        title: "What kind of commit type is it?"
        key: "Type"
        options:
          - name: "fix"
            description: "🐛 バグや不具合の修正"
            value: "fix :bug:"
          - name: "hotfix"
            description: "🚑 緊急のバグや不具合の修正"
            value: "hotfix :ambulance:"
          - name: "feat"
            description: "✨ 新機能の追加"
            value: "feat :sparkles:"
          - name: "update"
            description: "⬆️  既存機能に問題ないが処理の更新や改善"
            value: "update :arrow_up:"
          - name: "change"
            description: "💫 仕様変更による更新や改善"
            value: "change :dizzy:"
          - name: "docs"
            description: "📝 ドキュメントの更新や改善"
            value: "docs :memo:"
          - name: "style"
            description: "🎨 コードフォーマットの修正、UIのみの変更"
            value: "style :art:"
          - name: "refactor"
            description: "♻️  パフォーマンスの改善なしのコードの改善"
            value: "refactor :recycle:"
          - name: "rename"
            description: "✏️  ディレクトリ・ファイル名の変更"
            value: "rename :pencil2:"
          - name: "perf"
            description: "🚀 パフォーマンス改善"
            value: "perf :rocket:"
          - name: "move"
            description: "🚚 ディレクトリ・ファイルの移動"
            value: "move :truck:"
          - name: "delete"
            description: "🔥 ファイルやディレクトリの削除"
            value: "delete :fire:"
          - name: "upgrade"
            description: "🌟 バージョン更新"
            value: "upgrade :star2:"
          - name: "test"
            description: "💚 テスト・CIの追加や改善"
            value: "test :green_heart:"
          - name: "chore"
            description: "🔧 設定ファイルの変更や改善"
            value: "chore :wrench:"
          - name: "wip"
            description: "🚧 作業中"
            value: "wip :construction:"
      - type: "input"
        title: "Enter the Message"
        key: "Message"
        initialValue: ""
      - type: "confirm"
        title: "Commit"
        body: "Commit with the message '{{.Form.Type}} {{.Form.Message}}'. Is this okay?"
    command: "bash -c 'type=\"{{.Form.Type}}\"; message=\"{{.Form.Message}}\"; commit_message=\"$type $message\"; git commit -m \"$commit_message\"'"
    loadingText: "Committing..."
